In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
big_df = pd.read_csv('likens_project_results.csv')

In [3]:
df_best = big_df[big_df['GF_percent_rank'] == 1]

In [4]:
df_best

,GF_percent,GF_percent_rank,GF,GA,GD,PTS,President_Trophy,Conf_Best_Record,Division_Winner,Made_Playoffs,Won_1_Round,Won_2_Rounds,Won_3_Rounds,Won_Stanley_Cup
7,0.628637,1,251,218,33,107,0,1,1,1,1,0,0,0
35,0.615421,1,247,202,45,101,0,0,1,1,1,1,1,1
76,0.567179,1,244,206,38,106,0,1,1,1,0,0,0,0
101,0.633267,1,248,190,58,104,0,1,1,1,0,0,0,0
152,0.599585,1,266,208,58,102,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199845,0.595152,1,279,205,74,108,0,0,0,1,1,1,0,0
3199876,0.629601,1,248,181,67,111,1,1,1,1,1,1,1,1
3199912,0.589622,1,242,190,52,106,1,1,1,1,0,0,0,0
3199966,0.607309,1,262,244,18,89,0,0,0,0,0,0,0,0
3199998,0.625006,1,262,223,39,102,0,0,1,1,1,1,1,0

In [5]:
df_2ndbest = big_df[big_df['GF_percent_rank'] == 2]
df_3rdbest = big_df[big_df['GF_percent_rank'] == 3]
df_4thbest = big_df[big_df['GF_percent_rank'] == 4]
df_5thbest = big_df[big_df['GF_percent_rank'] == 5]
df_6thbest = big_df[big_df['GF_percent_rank'] == 6]
df_7thbest = big_df[big_df['GF_percent_rank'] == 7]
df_8thbest = big_df[big_df['GF_percent_rank'] == 8]
df_9thbest = big_df[big_df['GF_percent_rank'] == 9]
df_10thbest = big_df[big_df['GF_percent_rank'] == 10]
df_11thbest = big_df[big_df['GF_percent_rank'] == 11]
df_12thbest = big_df[big_df['GF_percent_rank'] == 12]
df_13thbest = big_df[big_df['GF_percent_rank'] == 13]
df_14thbest = big_df[big_df['GF_percent_rank'] == 14]
df_15thbest = big_df[big_df['GF_percent_rank'] == 15]
df_16thbest = big_df[big_df['GF_percent_rank'] == 16]
df_17thbest = big_df[big_df['GF_percent_rank'] == 17]
df_18thbest = big_df[big_df['GF_percent_rank'] == 18]
df_19thbest = big_df[big_df['GF_percent_rank'] == 19]
df_20thbest = big_df[big_df['GF_percent_rank'] == 20]
df_21stbest = big_df[big_df['GF_percent_rank'] == 21]
df_22ndbest = big_df[big_df['GF_percent_rank'] == 22]
df_23rdbest = big_df[big_df['GF_percent_rank'] == 23]
df_24thbest = big_df[big_df['GF_percent_rank'] == 24]
df_25thbest = big_df[big_df['GF_percent_rank'] == 25]
df_26thbest = big_df[big_df['GF_percent_rank'] == 26]
df_27thbest = big_df[big_df['GF_percent_rank'] == 27]
df_28thbest = big_df[big_df['GF_percent_rank'] == 28]
df_29thbest = big_df[big_df['GF_percent_rank'] == 29]
df_30thbest = big_df[big_df['GF_percent_rank'] == 30]
df_31stbest = big_df[big_df['GF_percent_rank'] == 31]
df_32ndbest = big_df[big_df['GF_percent_rank'] == 32]

In [5]:
def printing_results(df, rank):

    print(f'The average GF% of the {rank} team is: ', df['GF_percent'].mean())
    print(f'The {rank} team\'s average goal differential is: ', df['GD'].mean())
    print(f'The {rank} team averages the following standings points: ', df['PTS'].mean())
    print(f'The {rank} team\'s probability of winning the President\'s Trophy: ', df['President_Trophy'].mean())
    print(f'The {rank} team\'s probability of having the best record in their conferencce: ', df['Conf_Best_Record'].mean())
    print(f'The {rank} team\'s probability of winning their division: ', df['Division_Winner'].mean())
    print(f'The {rank} team\'s probability of making the playoffs: ', df['Made_Playoffs'].mean())
    print(f'The {rank} team\'s probability of winning 1 playoff round: ', df['Won_1_Round'].mean())
    print(f'The {rank} team\'s probability of winning 2 playoff rounds: ', df['Won_2_Rounds'].mean())
    print(f'The {rank} team\'s probability of winning 3 playoff rounds: ', df['Won_3_Rounds'].mean())
    print(f'The {rank} team\'s probability of winning the Stanley Cup: ', df['Won_Stanley_Cup'].mean())

In [10]:
printing_results(df_best, 'best')

The average GF% of the best team is:  0.6094860853443499
The best team's average goal differential is:  50.69278
The best team averages the following standings points:  104.87678
The best team's probability of winning the President's Trophy:  0.27432
The best team's probability of having the best record in their conferencce:  0.4014
The best team's probability of winning their division:  0.55425
The best team's probability of making the playoffs:  0.95284
The best team's probability of winning 1 playoff round:  0.64678
The best team's probability of winning 2 playoff rounds:  0.38758
The best team's probability of winning 3 playoff rounds:  0.27818
The best team's probability of winning the Stanley Cup:  0.17973

In [11]:
printing_results(df_2ndbest, '2nd best')

The average GF% of the 2nd best team is:  0.5871175616939656
The 2nd best team's average goal differential is:  40.57319
The 2nd best team averages the following standings points:  101.75789
The 2nd best team's probability of winning the President's Trophy:  0.15588
The 2nd best team's probability of having the best record in their conferencce:  0.27052
The 2nd best team's probability of winning their division:  0.42852
The 2nd best team's probability of making the playoffs:  0.91626
The 2nd best team's probability of winning 1 playoff round:  0.58298
The 2nd best team's probability of winning 2 playoff rounds:  0.3175
The 2nd best team's probability of winning 3 playoff rounds:  0.21086
The 2nd best team's probability of winning the Stanley Cup:  0.12223

In [12]:
printing_results(df_3rdbest, '3rd best')

The average GF% of the 3rd best team is:  0.5739857850101848
The 3rd best team's average goal differential is:  34.34857
The 3rd best team averages the following standings points:  99.83479
The 3rd best team's probability of winning the President's Trophy:  0.10747
The 3rd best team's probability of having the best record in their conferencce:  0.20419
The 3rd best team's probability of winning their division:  0.35483
The 3rd best team's probability of making the playoffs:  0.88148
The 3rd best team's probability of winning 1 playoff round:  0.53232
The 3rd best team's probability of winning 2 playoff rounds:  0.27409
The 3rd best team's probability of winning 3 playoff rounds:  0.1728
The 3rd best team's probability of winning the Stanley Cup:  0.09528

In [13]:
printing_results(df_4thbest, '4th best')

The average GF% of the 4th best team is:  0.5642944783595016
The 4th best team's average goal differential is:  29.96459
The 4th best team averages the following standings points:  98.46145
The 4th best team's probability of winning the President's Trophy:  0.08381
The 4th best team's probability of having the best record in their conferencce:  0.16695
The 4th best team's probability of winning their division:  0.30795
The 4th best team's probability of making the playoffs:  0.85
The 4th best team's probability of winning 1 playoff round:  0.49725
The 4th best team's probability of winning 2 playoff rounds:  0.24565
The 4th best team's probability of winning 3 playoff rounds:  0.15131
The 4th best team's probability of winning the Stanley Cup:  0.07923

In [14]:
printing_results(df_5thbest, '5th best')

The average GF% of the 5th best team is:  0.5563775550166201
The 5th best team's average goal differential is:  26.10938
The 5th best team averages the following standings points:  97.22411
The 5th best team's probability of winning the President's Trophy:  0.0634
The 5th best team's probability of having the best record in their conferencce:  0.13458
The 5th best team's probability of winning their division:  0.26335
The 5th best team's probability of making the playoffs:  0.81955
The 5th best team's probability of winning 1 playoff round:  0.46265
The 5th best team's probability of winning 2 playoff rounds:  0.22132
The 5th best team's probability of winning 3 playoff rounds:  0.13193
The 5th best team's probability of winning the Stanley Cup:  0.06736

In [15]:
printing_results(df_6thbest, '6th best')

The average GF% of the 6th best team is:  0.5495845649306881
The 6th best team's average goal differential is:  22.96697
The 6th best team averages the following standings points:  96.24934
The 6th best team's probability of winning the President's Trophy:  0.05145
The 6th best team's probability of having the best record in their conferencce:  0.11404
The 6th best team's probability of winning their division:  0.23446
The 6th best team's probability of making the playoffs:  0.79011
The 6th best team's probability of winning 1 playoff round:  0.43524
The 6th best team's probability of winning 2 playoff rounds:  0.20026
The 6th best team's probability of winning 3 playoff rounds:  0.11682
The 6th best team's probability of winning the Stanley Cup:  0.05643

In [16]:
printing_results(df_7thbest, '7th best')

The average GF% of the 7th best team is:  0.5435382493935906
The 7th best team's average goal differential is:  20.17653
The 7th best team averages the following standings points:  95.35065
The 7th best team's probability of winning the President's Trophy:  0.04256
The 7th best team's probability of having the best record in their conferencce:  0.09742
The 7th best team's probability of winning their division:  0.20884
The 7th best team's probability of making the playoffs:  0.76106
The 7th best team's probability of winning 1 playoff round:  0.40823
The 7th best team's probability of winning 2 playoff rounds:  0.1837
The 7th best team's probability of winning 3 playoff rounds:  0.10552
The 7th best team's probability of winning the Stanley Cup:  0.05143

In [17]:
printing_results(df_8thbest, '8th best')

The average GF% of the 8th best team is:  0.5379667354227333
The 8th best team's average goal differential is:  17.62401
The 8th best team averages the following standings points:  94.57198
The 8th best team's probability of winning the President's Trophy:  0.03588
The 8th best team's probability of having the best record in their conferencce:  0.08585
The 8th best team's probability of winning their division:  0.18818
The 8th best team's probability of making the playoffs:  0.73296
The 8th best team's probability of winning 1 playoff round:  0.38131
The 8th best team's probability of winning 2 playoff rounds:  0.16771
The 8th best team's probability of winning 3 playoff rounds:  0.09512
The 8th best team's probability of winning the Stanley Cup:  0.04532

In [18]:
printing_results(df_9thbest, '9th best')

The average GF% of the 9th best team is:  0.532840592083422
The 9th best team's average goal differential is:  15.12444
The 9th best team averages the following standings points:  93.74715
The 9th best team's probability of winning the President's Trophy:  0.02957
The 9th best team's probability of having the best record in their conferencce:  0.07238
The 9th best team's probability of winning their division:  0.16621
The 9th best team's probability of making the playoffs:  0.70224
The 9th best team's probability of winning 1 playoff round:  0.35943
The 9th best team's probability of winning 2 playoff rounds:  0.15473
The 9th best team's probability of winning 3 playoff rounds:  0.08498
The 9th best team's probability of winning the Stanley Cup:  0.04007

In [19]:
printing_results(df_10thbest, '10th best')

The average GF% of the 10th best team is:  0.5279913259700897
The 10th best team's average goal differential is:  12.86927
The 10th best team averages the following standings points:  93.03623
The 10th best team's probability of winning the President's Trophy:  0.02418
The 10th best team's probability of having the best record in their conferencce:  0.06309
The 10th best team's probability of winning their division:  0.14986
The 10th best team's probability of making the playoffs:  0.67578
The 10th best team's probability of winning 1 playoff round:  0.33657
The 10th best team's probability of winning 2 playoff rounds:  0.14026
The 10th best team's probability of winning 3 playoff rounds:  0.07514
The 10th best team's probability of winning the Stanley Cup:  0.03383

In [20]:
printing_results(df_11thbest, '11th best')

The average GF% of the 11th best team is:  0.5233374232317978
The 11th best team's average goal differential is:  10.6378
The 11th best team averages the following standings points:  92.30823
The 11th best team's probability of winning the President's Trophy:  0.01953
The 11th best team's probability of having the best record in their conferencce:  0.05263
The 11th best team's probability of winning their division:  0.13351
The 11th best team's probability of making the playoffs:  0.64581
The 11th best team's probability of winning 1 playoff round:  0.31636
The 11th best team's probability of winning 2 playoff rounds:  0.13046
The 11th best team's probability of winning 3 playoff rounds:  0.06981
The 11th best team's probability of winning the Stanley Cup:  0.03157

In [21]:
printing_results(df_12thbest, '12th best')

The average GF% of the 12th best team is:  0.5188916970473136
The 12th best team's average goal differential is:  8.8901
The 12th best team averages the following standings points:  91.75949
The 12th best team's probability of winning the President's Trophy:  0.01913
The 12th best team's probability of having the best record in their conferencce:  0.04975
The 12th best team's probability of winning their division:  0.12451
The 12th best team's probability of making the playoffs:  0.62306
The 12th best team's probability of winning 1 playoff round:  0.29896
The 12th best team's probability of winning 2 playoff rounds:  0.12015
The 12th best team's probability of winning 3 playoff rounds:  0.06242
The 12th best team's probability of winning the Stanley Cup:  0.02695

In [22]:
printing_results(df_13thbest, '13th best')

The average GF% of the 13th best team is:  0.5145535505341045
The 13th best team's average goal differential is:  6.76926
The 13th best team averages the following standings points:  91.10984
The 13th best team's probability of winning the President's Trophy:  0.01511
The 13th best team's probability of having the best record in their conferencce:  0.04153
The 13th best team's probability of winning their division:  0.11042
The 13th best team's probability of making the playoffs:  0.59457
The 13th best team's probability of winning 1 playoff round:  0.27732
The 13th best team's probability of winning 2 playoff rounds:  0.10964
The 13th best team's probability of winning 3 playoff rounds:  0.05619
The 13th best team's probability of winning the Stanley Cup:  0.02389

In [23]:
printing_results(df_14thbest, '14th best')

The average GF% of the 14th best team is:  0.5103112171308095
The 14th best team's average goal differential is:  4.82111
The 14th best team averages the following standings points:  90.4759
The 14th best team's probability of winning the President's Trophy:  0.01333
The 14th best team's probability of having the best record in their conferencce:  0.03759
The 14th best team's probability of winning their division:  0.10125
The 14th best team's probability of making the playoffs:  0.56725
The 14th best team's probability of winning 1 playoff round:  0.26188
The 14th best team's probability of winning 2 playoff rounds:  0.10165
The 14th best team's probability of winning 3 playoff rounds:  0.05123
The 14th best team's probability of winning the Stanley Cup:  0.02102

In [24]:
printing_results(df_15thbest, '15th best')

The average GF% of the 15th best team is:  0.5061669663740381
The 15th best team's average goal differential is:  2.94489
The 15th best team averages the following standings points:  89.86772
The 15th best team's probability of winning the President's Trophy:  0.01156
The 15th best team's probability of having the best record in their conferencce:  0.03294
The 15th best team's probability of winning their division:  0.09064
The 15th best team's probability of making the playoffs:  0.54223
The 15th best team's probability of winning 1 playoff round:  0.24588
The 15th best team's probability of winning 2 playoff rounds:  0.09364
The 15th best team's probability of winning 3 playoff rounds:  0.04646
The 15th best team's probability of winning the Stanley Cup:  0.01879

In [25]:
printing_results(df_16thbest, '16th best')

The average GF% of the 16th best team is:  0.5020411470214085
The 16th best team's average goal differential is:  0.87614
The 16th best team averages the following standings points:  89.21036
The 16th best team's probability of winning the President's Trophy:  0.00979
The 16th best team's probability of having the best record in their conferencce:  0.02822
The 16th best team's probability of winning their division:  0.08027
The 16th best team's probability of making the playoffs:  0.5123
The 16th best team's probability of winning 1 playoff round:  0.22812
The 16th best team's probability of winning 2 playoff rounds:  0.08528
The 16th best team's probability of winning 3 playoff rounds:  0.04125
The 16th best team's probability of winning the Stanley Cup:  0.01673

In [26]:
printing_results(df_17thbest, '17th best')

The average GF% of the 17th best team is:  0.4979231527779949
The 17th best team's average goal differential is:  -0.98409
The 17th best team averages the following standings points:  88.60602
The 17th best team's probability of winning the President's Trophy:  0.00774
The 17th best team's probability of having the best record in their conferencce:  0.02405
The 17th best team's probability of winning their division:  0.07331
The 17th best team's probability of making the playoffs:  0.48523
The 17th best team's probability of winning 1 playoff round:  0.21146
The 17th best team's probability of winning 2 playoff rounds:  0.07582
The 17th best team's probability of winning 3 playoff rounds:  0.03677
The 17th best team's probability of winning the Stanley Cup:  0.01438

In [27]:
printing_results(df_18thbest, '18th best')

The average GF% of the 18th best team is:  0.4938083074812675
The 18th best team's average goal differential is:  -2.82927
The 18th best team averages the following standings points:  87.99558
The 18th best team's probability of winning the President's Trophy:  0.00666
The 18th best team's probability of having the best record in their conferencce:  0.02126
The 18th best team's probability of winning their division:  0.06504
The 18th best team's probability of making the playoffs:  0.45921
The 18th best team's probability of winning 1 playoff round:  0.19711
The 18th best team's probability of winning 2 playoff rounds:  0.06937
The 18th best team's probability of winning 3 playoff rounds:  0.03258
The 18th best team's probability of winning the Stanley Cup:  0.01246

In [28]:
printing_results(df_19thbest, '19th best')

The average GF% of the 19th best team is:  0.4896416388930817
The 19th best team's average goal differential is:  -4.69478
The 19th best team averages the following standings points:  87.42419
The 19th best team's probability of winning the President's Trophy:  0.00559
The 19th best team's probability of having the best record in their conferencce:  0.01909
The 19th best team's probability of winning their division:  0.0595
The 19th best team's probability of making the playoffs:  0.43453
The 19th best team's probability of winning 1 playoff round:  0.18214
The 19th best team's probability of winning 2 playoff rounds:  0.06503
The 19th best team's probability of winning 3 playoff rounds:  0.03106
The 19th best team's probability of winning the Stanley Cup:  0.01205

In [29]:
printing_results(df_20thbest, '20th best')

The average GF% of the 20th best team is:  0.48540980157118857
The 20th best team's average goal differential is:  -6.69067
The 20th best team averages the following standings points:  86.73455
The 20th best team's probability of winning the President's Trophy:  0.00488
The 20th best team's probability of having the best record in their conferencce:  0.016
The 20th best team's probability of winning their division:  0.05021
The 20th best team's probability of making the playoffs:  0.40457
The 20th best team's probability of winning 1 playoff round:  0.16602
The 20th best team's probability of winning 2 playoff rounds:  0.05793
The 20th best team's probability of winning 3 playoff rounds:  0.02605
The 20th best team's probability of winning the Stanley Cup:  0.00965

In [30]:
printing_results(df_21stbest, '21st best')

The average GF% of the 21st best team is:  0.48109216942488797
The 21st best team's average goal differential is:  -8.78207
The 21st best team averages the following standings points:  86.08533
The 21st best team's probability of winning the President's Trophy:  0.00427
The 21st best team's probability of having the best record in their conferencce:  0.01416
The 21st best team's probability of winning their division:  0.04641
The 21st best team's probability of making the playoffs:  0.37876
The 21st best team's probability of winning 1 playoff round:  0.1529
The 21st best team's probability of winning 2 playoff rounds:  0.0513
The 21st best team's probability of winning 3 playoff rounds:  0.0225
The 21st best team's probability of winning the Stanley Cup:  0.00789

In [31]:
printing_results(df_22ndbest, '22nd best')

The average GF% of the 22nd best team is:  0.47662549596245235
The 22nd best team's average goal differential is:  -10.74763
The 22nd best team averages the following standings points:  85.42162
The 22nd best team's probability of winning the President's Trophy:  0.00358
The 22nd best team's probability of having the best record in their conferencce:  0.01117
The 22nd best team's probability of winning their division:  0.04025
The 22nd best team's probability of making the playoffs:  0.35046
The 22nd best team's probability of winning 1 playoff round:  0.1367
The 22nd best team's probability of winning 2 playoff rounds:  0.04503
The 22nd best team's probability of winning 3 playoff rounds:  0.01994
The 22nd best team's probability of winning the Stanley Cup:  0.00735

In [32]:
printing_results(df_23rdbest, '23rd best')

The average GF% of the 23rd best team is:  0.4719930788397755
The 23rd best team's average goal differential is:  -13.04094
The 23rd best team averages the following standings points:  84.69815
The 23rd best team's probability of winning the President's Trophy:  0.00271
The 23rd best team's probability of having the best record in their conferencce:  0.00951
The 23rd best team's probability of winning their division:  0.03344
The 23rd best team's probability of making the playoffs:  0.32288
The 23rd best team's probability of winning 1 playoff round:  0.12416
The 23rd best team's probability of winning 2 playoff rounds:  0.03982
The 23rd best team's probability of winning 3 playoff rounds:  0.01759
The 23rd best team's probability of winning the Stanley Cup:  0.00648

In [33]:
printing_results(df_24thbest, '24th best')

The average GF% of the 24th best team is:  0.4671189525645069
The 24th best team's average goal differential is:  -15.23926
The 24th best team averages the following standings points:  84.00557
The 24th best team's probability of winning the President's Trophy:  0.002
The 24th best team's probability of having the best record in their conferencce:  0.00789
The 24th best team's probability of winning their division:  0.03072
The 24th best team's probability of making the playoffs:  0.29731
The 24th best team's probability of winning 1 playoff round:  0.11196
The 24th best team's probability of winning 2 playoff rounds:  0.03529
The 24th best team's probability of winning 3 playoff rounds:  0.01531
The 24th best team's probability of winning the Stanley Cup:  0.00508

In [34]:
printing_results(df_25thbest, '25th best')

The average GF% of the 25th best team is:  0.4619418107695984
The 25th best team's average goal differential is:  -17.58924
The 25th best team averages the following standings points:  83.22483
The 25th best team's probability of winning the President's Trophy:  0.00186
The 25th best team's probability of having the best record in their conferencce:  0.00681
The 25th best team's probability of winning their division:  0.02673
The 25th best team's probability of making the playoffs:  0.26988
The 25th best team's probability of winning 1 playoff round:  0.09843
The 25th best team's probability of winning 2 playoff rounds:  0.02956
The 25th best team's probability of winning 3 playoff rounds:  0.0122
The 25th best team's probability of winning the Stanley Cup:  0.00409

In [35]:
printing_results(df_26thbest, '26th best')

The average GF% of the 26th best team is:  0.4563955228701671
The 26th best team's average goal differential is:  -20.30839
The 26th best team averages the following standings points:  82.35493
The 26th best team's probability of winning the President's Trophy:  0.00116
The 26th best team's probability of having the best record in their conferencce:  0.00493
The 26th best team's probability of winning their division:  0.02105
The 26th best team's probability of making the playoffs:  0.23788
The 26th best team's probability of winning 1 playoff round:  0.08443
The 26th best team's probability of winning 2 playoff rounds:  0.02486
The 26th best team's probability of winning 3 playoff rounds:  0.00983
The 26th best team's probability of winning the Stanley Cup:  0.00301

In [36]:
printing_results(df_27thbest, '27th best')

The average GF% of the 27th best team is:  0.450347880035754
The 27th best team's average goal differential is:  -23.04184
The 27th best team averages the following standings points:  81.48433
The 27th best team's probability of winning the President's Trophy:  0.00093
The 27th best team's probability of having the best record in their conferencce:  0.00411
The 27th best team's probability of winning their division:  0.01696
The 27th best team's probability of making the playoffs:  0.20944
The 27th best team's probability of winning 1 playoff round:  0.07229
The 27th best team's probability of winning 2 playoff rounds:  0.02155
The 27th best team's probability of winning 3 playoff rounds:  0.00847
The 27th best team's probability of winning the Stanley Cup:  0.00265

In [37]:
printing_results(df_28thbest, '28th best')

The average GF% of the 28th best team is:  0.44352399176263546
The 28th best team's average goal differential is:  -26.18444
The 28th best team averages the following standings points:  80.43987
The 28th best team's probability of winning the President's Trophy:  0.00062
The 28th best team's probability of having the best record in their conferencce:  0.00302
The 28th best team's probability of winning their division:  0.01397
The 28th best team's probability of making the playoffs:  0.18168
The 28th best team's probability of winning 1 playoff round:  0.06058
The 28th best team's probability of winning 2 playoff rounds:  0.01684
The 28th best team's probability of winning 3 playoff rounds:  0.00656
The 28th best team's probability of winning the Stanley Cup:  0.00199

In [38]:
printing_results(df_29thbest, '29th best')

The average GF% of the 29th best team is:  0.4356401340224358
The 29th best team's average goal differential is:  -29.78715
The 29th best team averages the following standings points:  79.24885
The 29th best team's probability of winning the President's Trophy:  0.00052
The 29th best team's probability of having the best record in their conferencce:  0.00215
The 29th best team's probability of winning their division:  0.01036
The 29th best team's probability of making the playoffs:  0.1478
The 29th best team's probability of winning 1 playoff round:  0.04756
The 29th best team's probability of winning 2 playoff rounds:  0.01325
The 29th best team's probability of winning 3 playoff rounds:  0.00496
The 29th best team's probability of winning the Stanley Cup:  0.00139

In [39]:
printing_results(df_30thbest, '30th best')

The average GF% of the 30th best team is:  0.4259998318838955
The 30th best team's average goal differential is:  -34.29038
The 30th best team averages the following standings points:  77.83696
The 30th best team's probability of winning the President's Trophy:  0.00028
The 30th best team's probability of having the best record in their conferencce:  0.00141
The 30th best team's probability of winning their division:  0.00776
The 30th best team's probability of making the playoffs:  0.11891
The 30th best team's probability of winning 1 playoff round:  0.03647
The 30th best team's probability of winning 2 playoff rounds:  0.00958
The 30th best team's probability of winning 3 playoff rounds:  0.00341
The 30th best team's probability of winning the Stanley Cup:  0.0009

In [40]:
printing_results(df_31stbest, '31st best')

The average GF% of the 31st best team is:  0.4129388943153502
The 31st best team's average goal differential is:  -40.42747
The 31st best team averages the following standings points:  75.8536
The 31st best team's probability of winning the President's Trophy:  0.00013
The 31st best team's probability of having the best record in their conferencce:  0.00088
The 31st best team's probability of winning their division:  0.00471
The 31st best team's probability of making the playoffs:  0.08501
The 31st best team's probability of winning 1 playoff round:  0.02521
The 31st best team's probability of winning 2 playoff rounds:  0.00636
The 31st best team's probability of winning 3 playoff rounds:  0.0019
The 31st best team's probability of winning the Stanley Cup:  0.00051

In [41]:
printing_results(df_32ndbest, 'worst')

The average GF% of the worst team is:  0.39065175922876527
The worst team's average goal differential is:  -50.75141
The worst team averages the following standings points:  72.52655
The worst team's probability of winning the President's Trophy:  0.0001
The worst team's probability of having the best record in their conferencce:  0.00048
The worst team's probability of winning their division:  0.00253
The worst team's probability of making the playoffs:  0.04895
The worst team's probability of winning 1 playoff round:  0.01247
The worst team's probability of winning 2 playoff rounds:  0.00252
The worst team's probability of winning 3 playoff rounds:  0.00085
The worst team's probability of winning the Stanley Cup:  0.00026

In [42]:
df_pres = big_df[big_df['President_Trophy'] == 1]

In [43]:
df_pres

,GF_percent,GF_percent_rank,GF,GA,GD,PTS,President_Trophy,Conf_Best_Record,Division_Winner,Made_Playoffs,Won_1_Round,Won_2_Rounds,Won_3_Rounds,Won_Stanley_Cup
29,0.624592,2,278,211,67,111,1,1,1,1,1,0,0,0
34,0.563355,4,250,205,45,102,1,1,1,1,1,0,0,0
73,0.523345,10,268,201,67,111,1,1,1,1,1,1,1,0
110,0.547655,4,251,214,37,110,1,1,1,1,0,0,0,0
144,0.594359,2,263,211,52,112,1,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199867,0.567246,2,275,210,65,109,1,1,1,1,1,0,0,0
3199876,0.629601,1,248,181,67,111,1,1,1,1,1,1,1,1
3199912,0.589622,1,242,190,52,106,1,1,1,1,0,0,0,0
3199942,0.528461,7,259,215,44,113,1,1,1,1,1,1,1,1
3199991,0.510153,19,268,238,30,108,1,1,1,1,1,0,0,0

In [44]:
print(f'The probability that the President\'s Trophy winner wins the Stanley Cup: ', df_pres['Won_Stanley_Cup'].mean())

The probability that the President's Trophy winner wins the Stanley Cup:  0.1279

In [2]:
sens_df_likens = pd.read_csv('likens_project_sens_likens.csv')

In [3]:
sens_likens_best = sens_df_likens[sens_df_likens['GF_percent_rank'] == 1]

In [6]:
printing_results(sens_likens_best, 'best')

The average GF% of the best team is:  0.5620387758344443
The best team's average goal differential is:  28.85264
The best team averages the following standings points:  98.1809
The best team's probability of winning the President's Trophy:  0.15413
The best team's probability of having the best record in their conferencce:  0.24494
The best team's probability of winning their division:  0.37612
The best team's probability of making the playoffs:  0.8438
The best team's probability of winning 1 playoff round:  0.51907
The best team's probability of winning 2 playoff rounds:  0.28293
The best team's probability of winning 3 playoff rounds:  0.18787
The best team's probability of winning the Stanley Cup:  0.11217

In [7]:
sens_df_20222025 = pd.read_csv('likens_project_sens_20222025.csv')

In [9]:
sens_20222025_best = sens_df_20222025[sens_df_20222025['GF_percent_rank'] == 1]

In [11]:
printing_results(sens_20222025_best, 'best')

The average GF% of the best team is:  0.6227392504918378
The best team's average goal differential is:  56.9301
The best team averages the following standings points:  106.70583
The best team's probability of winning the President's Trophy:  0.30736
The best team's probability of having the best record in their conferencce:  0.44089
The best team's probability of winning their division:  0.59397
The best team's probability of making the playoffs:  0.96633
The best team's probability of winning 1 playoff round:  0.67707
The best team's probability of winning 2 playoff rounds:  0.41444
The best team's probability of winning 3 playoff rounds:  0.30018
The best team's probability of winning the Stanley Cup:  0.19583